### ISSUE TITLE
Eml files are not created on Windows

### ISSUE THREAD

**Issue by vovancho** [geekdevs/swift-mailer-extensions#2]
https://github.com/geekdevs/swift-mailer-extensions/blob/c1bbcf8a88b769ac7b2c97079c4e052a412d5ddc/src/SwiftMailer/Transport/FileTransport.php#L123

This code does not work on Windows. On Windows, you cannot create a file with a colon in the name.

`$fileName = $this->path.'/'.date('Y-m-d H-i-s');`

**Comment by geekdevs** [comment]
@vovancho Thanks! I've been using it for years but never on Windows :) 
Released a fix for this.
